{{- if not .Values.rollouts.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{ include "k8s-common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "k8s-common.labels.matchLabels" . | nindent 8 }}
      {{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations: {{ include "k8s-common.annotations.podAnnotations" . | trim | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "k8s-common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.podAffinityPreset }}
        podAffinity: {{- include "k8s-common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "k8s-common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.nodeAffinityPreset.type }}
        nodeAffinity: {{- include "k8s-common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "k8s-common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "k8s-common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-common.serviceAccount.name" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- range .Values.initContainers }}
        {{- $values := dict "Values" . "Release" $.Release "Template" $.Template -}}
        {{- $name := required "nameOverride is required for the init containers" $values.Values.nameOverride }}
        {{- $_ := set $values.Values "global" $.Values.global -}}
        {{- $__ := set $values.Values "volumes" ($values.Values.volumes | default $.Values.volumes) -}}
        {{- include "k8s-common.containers.container" $values | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        {{- include "k8s-common.containers.container" . | nindent 8 }}
        {{- if .Values.sidecarContainers }}
        {{- range .Values.sidecarContainers }}
        {{/* Define configuration for subobjects (containers) with inputs from root($) context*/}}
        {{- $values := dict "Values" . "Release" $.Release "Template" $.Template -}}
        {{- $name := required "nameOverride is required for the sidecar containers" $values.Values.nameOverride }}
        {{- $_ := set $values.Values "global" $.Values.global -}}
        {{- $__ := set $values.Values "volumes" ($values.Values.volumes | default $.Values.volumes) -}}
        {{- include "k8s-common.containers.container" $values | nindent 8 }}
        {{- end }}
        {{- end }}
      volumes: {{- include "k8s-common.volume.definitions" . | nindent 8 }}
      {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "k8s-common.names.fullname" . }}
      {{- end }}
{{- end }}
