apiVersion: v2
name: configmaps
version: 1.0.0
description: The chart for creating configmaps.
type: application
dependencies:
  - name: k8s-common
    version: 1.0.0
    repository: https://next-gen-infrastructure.github.io/kubernetes-helm-charts
home: https://next-gen-infrastructure.github.io/kubernetes-helm-charts
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/stable/configmaps
maintainers:
  - name: Alexander Dobrodey
    url: https://github.com/ADobrodey
